### ISSUE TITLE
Enable passing babel-plugin-react-intl options.

### ISSUE THREAD

**Issue by Filson14** [akameco/extract-react-intl#18]
**Do you want to request a *feature* or report a *bug*?:**
Feature

**What is the expected behavior?:**
I have a case where I've wrapped react-intl with my own module with some custom functions and components to manage internationalization. I don't want the need to import some elements from it and some from react-intl. I prefer to use just one source. I've mentioned it in [this issue](https://github.com/akameco/extract-react-intl-messages/issues/27).

**babel-plugin-react-intl** accepts few [options](https://github.com/yahoo/babel-plugin-react-intl#options) to manipulate extracting process. With **extract-react-intl** context, most of them are not so helpful (especially if we assume using it with by **extract-react-intl-messages**), but one is. I mean _moduleSourceName_ which lets plugin to know from where `defineMessages` or `<FormattedMessage />` is imported. Of course, default is `react-intl` but in some cases one may want to use custom module.

**Suggested solution:**
It would be great to be able to pass custom module name to **extract-react-intl** which can forward it to **babel-plugin-react-intl** (I've tested it locally, simply by explicitly adding options to unshifted preset in the source code and it works).

Same thing would fit **extract-react-intl-messages**.

@akameco, I can try to manage some changes if you want (but never done that on someones github repo :wink: ).

**Comment by akameco** [comment]
@Filson14 Sounds good.  Could you send a PR?

**Comment by Filson14** [comment]
Done in here https://github.com/akameco/extract-react-intl/pull/20
I wait for Your thoughts.
