### ISSUE TITLE
babel-plugin-react-intl execution order can cause unexpected errors

### ISSUE THREAD

**Issue by bradbarrow** [akameco/extract-react-intl#9]
- version: 0.5.1
- `node` version: 8.9.3
- `npm` (or `yarn`) version: yarn 1.3.2

**Do you want to request a *feature* or report a *bug*?:**

Suggest a feature

**What is the current behavior?:**

Since `extract-react-intl` [pushes](https://github.com/akameco/extract-react-intl/blob/master/index.js#L70) `babel-plugin-react-intl` into the plugins list, it will be executed ahead of any user configured babel presets.

So if I have a preset:

```
// my-preset.js
{
  "presets": ["env", "stage-3"],
  "plugins": ["react-intl-auto"]
}
```

and I use that in my projects `.babelrc`:

```
//.babelrc
{
  presets: ["my-preset"]
}
```

then because of this line:

```
plugins.push(require('babel-plugin-react-intl').default)
```

The following are the options passed to `transformFile` inside `extract-react-intl`:

```
{
  presets: ['/some/path/to/my-preset.js'],
  plugins: ['/some/path/to/babel-plugin-react-intl/index.js'],
}
```

> Babel prioritizes plugins in the top level config BEFORE plugins in any presets.

The **result** in my case above is that `babel-plugin-react-intl` is called BEFORE `babel-plugin-react-intl-auto` which is problematic.

If I had the following `.babelrc` file it will work because the plugins aren't in a preset:

```
//.babelrc
{
  presets: ["my-preset"],
  plugins: ["react-intl-auto"],
}
```

**What is the ~expected~ desired behavior?:**

I'd love to find a way for all the user's `babel` config/presets/plugins to be run before `babel-plugin-react-intl` so that I don't have to worry about the order of my own babel config to make this tool work.

**Suggested solution:**

If you were to unshift `babel-plugin-react-intl` into the presets instead of plugins, it'd make it lower in the execution order for babel:

```diff
- plugins.push(require('babel-plugin-react-intl').default)
+ presets.unshift({ plugins: [require('babel-plugin-react-intl').default] })
```

**Comment by akameco** [comment]
@bradbarrow Make sense.
Welcome PR😄

**Comment by bradbarrow** [comment]
Done @akameco 👌
